### ISSUE TITLE
Instagram 308.0.0.0.71 Alpha Crashes on Launch

### ISSUE THREAD

**Issue by kero3009destiny** [xHookman/IGExperimentsPatcher#2]
Patch is successful yet the app crashes on launch. Patched and signed correctly, uploaded the APK to ApkMirror and waiting for approval rn.

**Comment by xHookman** [comment]
Oh :/ Can you try with the latest version ? May be patching has been fixed for that case too
This problem didn't happened to me for the moment, i invite you to try with a newer instagram apk in the meantime
