### ISSUE TITLE
Instagram 310.0.0.0.242 alpha building patch error

### ISSUE THREAD

**Issue by dishapatel010** [xHookman/IGExperimentsPatcher#3]
[Instagram 310.0.0.0.130 alpha (arm64-v8a) (560-640dpi) (Android 9.0+)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-130-release/instagram-310-0-0-0-130-android-apk-download/)

`Enabling experiments...

No method found for experiments

##[error]Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null

java.base/java.lang.String.startsWith(String.java:2259)

java.base/java.lang.String.startsWith(String.java:2302)

com.chacha.igexperimentspatcher.Patcher.findClassToPatch(Patcher.java:92)

com.chacha.igexperimentspatcher.Patcher.enableExperiments(Patcher.java:154)

com.chacha.igexperimentspatcher.Patcher.patch(Patcher.java:29)

com.chacha.igexperimentspatcher.Main.main(Main.java:17)

##[error]Process completed with exit code 1.`

**Comment by dishapatel010** [comment]
https://github.com/xdwtf/IGExperimentsPatcher/actions/runs/6915022150

310.0.0.0.139 alpha worked

**Comment by xHookman** [comment]
> [Instagram 310.0.0.0.130 alpha (arm64-v8a) (560-640dpi) (Android 9.0+)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-130-release/instagram-310-0-0-0-130-android-apk-download/)
> 
> `Enabling experiments...
> 
> No method found for experiments
> 
> ##[error]Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
> 
> java.base/java.lang.String.startsWith(String.java:2259)
> 
> java.base/java.lang.String.startsWith(String.java:2302)
> 
> com.chacha.igexperimentspatcher.Patcher.findClassToPatch(Patcher.java:92)
> 
> com.chacha.igexperimentspatcher.Patcher.enableExperiments(Patcher.java:154)
> 
> com.chacha.igexperimentspatcher.Patcher.patch(Patcher.java:29)
> 
> com.chacha.igexperimentspatcher.Main.main(Main.java:17)
> 
> ##[error]Process completed with exit code 1.`

Hi yeah i already seen this error, and i know why. I'm sorry i don't really have the time for the moment, i'll fix it when i have the courage to rewrite better code :)

Have a nice day!

**Comment by dishapatel010** [comment]
310.0.0.0.242 I tried to build it via patcher but it says same error 
It happens on every new build

> [Instagram 310.0.0.0.130 alpha (arm64-v8a) (560-640dpi) (Android 9.0+)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-130-release/instagram-310-0-0-0-130-android-apk-download/)
> 
> `Enabling experiments...
> 
> No method found for experiments
> 
> ##[error]Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
> 
> java.base/java.lang.String.startsWith(String.java:2259)
> 
> java.base/java.lang.String.startsWith(String.java:2302)
> 
> com.chacha.igexperimentspatcher.Patcher.findClassToPatch(Patcher.java:92)
> 
> com.chacha.igexperimentspatcher.Patcher.enableExperiments(Patcher.java:154)
> 
> com.chacha.igexperimentspatcher.Patcher.patch(Patcher.java:29)
> 
> com.chacha.igexperimentspatcher.Main.main(Main.java:17)
> 
> ##[error]Process completed with exit code 1.`

**Comment by dishapatel010** [comment]
> > [Instagram 310.0.0.0.130 alpha (arm64-v8a) (560-640dpi) (Android 9.0+)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-130-release/instagram-310-0-0-0-130-android-apk-download/)
> > `Enabling experiments...
> > No method found for experiments
> > ##[error]Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
> > java.base/java.lang.String.startsWith(String.java:2259)
> > java.base/java.lang.String.startsWith(String.java:2302)
> > com.chacha.igexperimentspatcher.Patcher.findClassToPatch(Patcher.java:92)
> > com.chacha.igexperimentspatcher.Patcher.enableExperiments(Patcher.java:154)
> > com.chacha.igexperimentspatcher.Patcher.patch(Patcher.java:29)
> > com.chacha.igexperimentspatcher.Main.main(Main.java:17)
> > ##[error]Process completed with exit code 1.`
> 
> Hi yeah i already seen this error, and i know why. I'm sorry i don't really have the time for the moment, i'll fix it when i have the courage to rewrite better code :)
> 
> Have a nice day!

Okay! May Force Guide You.

**Comment by xHookman** [comment]
> 310.0.0.0.242 I tried to build it via patcher but it says same error It happens on every new build
> 
> > [Instagram 310.0.0.0.130 alpha (arm64-v8a) (560-640dpi) (Android 9.0+)](https://www.apkmirror.com/apk/instagram/instagram-instagram/instagram-instagram-310-0-0-0-130-release/instagram-310-0-0-0-130-android-apk-download/)
> > `Enabling experiments...
> > No method found for experiments
> > ##[error]Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.length()" because "prefix" is null
> > java.base/java.lang.String.startsWith(String.java:2259)
> > java.base/java.lang.String.startsWith(String.java:2302)
> > com.chacha.igexperimentspatcher.Patcher.findClassToPatch(Patcher.java:92)
> > com.chacha.igexperimentspatcher.Patcher.enableExperiments(Patcher.java:154)
> > com.chacha.igexperimentspatcher.Patcher.patch(Patcher.java:29)
> > com.chacha.igexperimentspatcher.Main.main(Main.java:17)
> > ##[error]Process completed with exit code 1.`

Wow i just tried with the apk from your link and it worked for me :/ Can you try with the latest patcher version may be ?
Also I'm using Windows, I haven't tested it on Linux yet but it should work like Windows normally

**Comment by xHookman** [comment]
Okay i just tried on Ubuntu and i get same error as you, i've just found the problem
Edit: i uploaded an update :) Thanks for your report
